pull_request_rules: []
merge_protections:
  - name: VM6 Long Running Protection
    if: []
    success_conditions:
      - check-success = vm6-auto-merge-ci
merge_protections_settings:
  reporting_method: check-runs
  post_comment: true
  auto_merge_conditions: true
